name: meduad_mvae_vq
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.62.1
  - openssl=3.5.4
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - prompt-toolkit=3.0.52
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.7.14
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - click-option-group==0.5.7
      - clinicadl==2.0.0rc1
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - coverage==7.9.2
      - cycler==0.12.1
      - deprecated==1.2.18
      - distlib==0.4.0
      - einops==0.8.1
      - execnet==2.1.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - grpcio==1.73.1
      - humanize==4.12.3
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - identify==2.6.12
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lpips==0.1.4
      - lxml==6.0.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - monai==1.5.0
      - mpmath==1.3.0
      - networkx==3.5
      - nibabel==5.3.2
      - nilearn==0.9.2
      - nodeenv==1.9.1
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==24.2
      - pandas==2.3.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pre-commit==4.2.0
      - protobuf==4.25.8
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pytest==8.4.1
      - pytest-cov==3.0.0
      - pytest-timeout==2.4.0
      - pytest-xdist==3.8.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==14.0.0
      - scikit-image==0.24.0
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - submitit==1.5.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - toml==0.10.2
      - torch==2.6.0
      - torchio==0.20.19
      - torchsummary==1.5.1
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==1.26.20
      - virtualenv==20.32.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
