_target_: models.vp_sde.model.networks.UNet1DModel

sample_size: 265
in_channels:  1
out_channels:  1
extra_in_channels: 0
use_timestep_embedding: true
block_out_channels: [32, 32, 64]
act_fn: silu
norm_num_groups: 8
layers_per_block: 1
downsample_each_block: false