_target_: trainers.adversarial_trainer.AdversarialTrainer
_partial_: true
output_dir: ${hydra:run.dir}
train_config:
  n_epoch: 100
  batch_size: 32
  device: ${device}
  clip_grad_norm: 1.0
  eval_patience: 5
  start_epoch: 0
  accumulate_grad_batches: 1
  disc_steps_per_gen: 1
  gen_steps_per_disc: 5
  ema_update_interval: 1