# configs/train/trainer.yaml

_target_: trainers.Trainer 
_partial_: true
output_dir: ${hydra:run.dir}
train_config:
  n_epoch: 100
  device: ${device} 
  clip_grad_norm: 1.0
  eval_patience: 10
  start_epoch: 0
  accumulate_grad_batches: 1
  use_amp: true
  use_tqdm: true