
defaults:
  - /network/3D_encoder@encoder
  - /network/3D_decoder@decoder
  - _self_

_target_: multivae.models.CVAE

model_config:
  _target_: multivae.models.CVAEConfig
  main_modality: pet_linear
  conditioning_modalities: []
  latent_dim: 256
  decoder_dist: normal
  beta: 10.0
  sigma_variation: null
  sparse: false
  log_sigma_init: -2.0
  log_alpha_init: 0.0
  mean_over_batch: false

