_target_: models.vqvae_spatial.model.networks.architectures3d.Decoder3d
latent_dim: ${model.model_config.latent_dim}
n_blocks: 5
n_subblocks: 1
activation: silu
block: conv
last_conv: true
merge_method: concat
output_decoder_actv: identity
flatten: false